<?php echo $this->render('header.phtml');?>
<?php echo $this->render('navbar.phtml');?>
<div class="container">

	<form method="POST" id='newRequestForm' name='newRequestForm' action="<?php echo $this->baseUrl ?>/validate/validate" enctype="multipart/form-data">

		<div id='requestNumber'>
			<b>Request Number: N/A</b>
		</div>
		<div class="panel panel-info">
			<div class="panel-heading"><h4>Company Details</h4></div>

		
		<div class="panel-body" id="company">
		    <div class="row">
		        <div class="col-md-6 pull-left">
					<table>
						<tr>
							<td><label for="companyCode">Company Code *</label></td>
							<td><input type="text" name="companyCode" value="<?= isset($this->currentForm[0]) ?  $this->currentForm[0] : '4440' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[0]){?>
								<span class="error"><?php echo "plz enter four digit code"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label title='One Time Vendor?  Estimated Annual Spend?' for="businessJustification">Business Justification * </label></td>
							<td><textarea title='One Time Vendor?  Estimated Annual Spend?' id="businessJustification" 
		            	name="businessJustification" required><?= isset($this->params['businessJustification']) ?  
		            		$this->params['businessJustification'] : 'One Time Vendor?  Estimated Annual Spend?' ?></textarea></td>
						</tr>
					</table>
				</div>
		        <div class="col-md-6 pull-right">
					<table>
						<tr>
							<td><label for="purchasingOrganisation">Purchasing Organisation *</label></td>
							<td><input type="text" name="purchasingOrganisation" value="<?= isset($this->currentForm[1]) ?  $this->currentForm[1] : 'UK01' ?>" required/></td>

						<td>  
								<?php if($this->errorLog[1]){?>
								<span class="error"><?php echo "Only four digit number is allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="categoryId">Category *</label></td>
							<td><select name="categoryId" id="categoryId">
								<?php 
								foreach ($this->categories as $category){

									$selected = (isset($this->params['categoryId']) && $this->params['categoryId'] == $category->getCategoryId()) ? 'selected="selected"' : '';
									echo "<option value='".$category->getCategoryId()."' ".$selected.">".$category->getCategoryName()."</option>";
								}
								?>

							</select></td>
						</tr>
						<tr>
							<td><label for="freightForwarder">Freight Forwarder</label></td>
							<td><select id='freightForwarder' name='freightForwarder' >
								<option value='0' <?= (isset($this->params['freightForwarder']) && $this->params['freightForwarder'] == 0) ? 'selected="selected"' : '';?>>No</option>
								<option value='1' <?= (isset($this->params['freightForwarder']) && $this->params['freightForwarder'] == 1) ? 'selected="selected"' : '';?>>Yes</option>
							</select></td>
						</tr>
					</table>
		        </div>
		    </div>    
		</div>
	</div>	
		
		<div class="panel panel-info">
			<div class="panel-heading"><h4>Contact Details</h4></div>
			
			<div class="panel-body" id="contact">
				<div class="row">
				  
					<div class="col-md-6 pull-left">
						<table>
							<tr>
								<td><label for="name">Vendor Name *</label></td>
								<td><input type="text" name="name" value="<?= isset($this->currentForm[2]) ?  $this->currentForm[2] : '' ?>" required/></td>
								<td>  
								<?php if($this->errorLog[2]){?>
								<span class="error"><?php echo "Enter valid name"?> </span>
<?php }?></td>
							</tr>
							<tr>
								<td><label for="contactAddress">Address 1 *</label></td>
								<td><input type="textarea" name="contactAddress"  id="contactAddress" value="<?= isset($this->params['contactAddress']) ?  $this->params['contactAddress'] : '' ?>" required/></td>
							</tr>
							<tr>
								<td><label for="contactAddress2">Address 2 </label></td>
								<td><input type="textarea" name="contactAddress2" id="contactAddress2" value="<?= isset($this->params['contactAddress2']) ?  $this->params['contactAddress2'] : '' ?>" /></td>
							</tr>
							<tr>
								<td><label for="contactCity">City *</label></td>
								<td><input type="text" name="contactCity" id="contactCity" value="<?= isset($this->currentForm[3]) ?  $this->currentForm[3] : '' ?>" required/></td>
								<td>  
								<?php if($this->errorLog[3]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
							</tr>
							<tr>
								<td><label for="contactCounty">County/Region *</label></td>
								<td><input type="text" name="contactCounty" id="contactCounty" value="<?= isset($this->currentForm[4]) ?  $this->currentForm[4] : '' ?>" required/></td>
								<td>  
								<?php if($this->errorLog[4]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
							</tr>
							<tr>
								<td><label for="contactPostcode">Postcode *</label></td>
								<td><input type="number" name="contactPostcode" id="contactPostcode" value="<?= isset($this->params['contactPostcode']) ?  $this->params['contactPostcode'] : '' ?>" required/></td>
							</tr>
						</table>
					</div>
					
					<div class="col-md-6 pull-right">
						<table>
							<tr>
								<td><label for="contactCountry">Country *</label></td>
								<td><select name="contactCountry" id="contactCountry" alt-input='contactAlt' class='countryField'>
									<?php 
									
									$this->params['contactCountry'] = (isset($this->params['contactCountry'])) ? $this->params['contactCountry'] : 'gb';
									
									foreach($this->countries as $code => $name) {
										
										$selected = (isset($this->params['contactCountry']) && $this->params['contactCountry'] == $code) ? 'selected="selected"' : '';
										
										echo '<option value="'.$code.'" '.$selected.' >'.$name.'</option>';
									  
									} ?>

								</select> </td>
							</tr>
							<tr>
								<td><label for="contactOtherCountry" class='otherCountryField contactAlt'>Please Specify </label></td>
								<td><input type="text" class='otherCountryField contactAlt' name="contactOtherCountry" id="contactOtherCountry" <?= isset($this->currentForm[5]) ?  $this->currentForm[5] : '' ?> /></td>
								<td>  
								<?php if($this->errorLog[5]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
							</tr>	
							<tr>
								<td><label for="contactTelephone">Telephone *</label></td>
								<td><input type="text" oninvalid="setCustomValidity('Plz enter valid telephone number ')" name="contactTelephone" id="contactTelephone" value="<?= isset($this->params['contactTelephone']) ?  $this->params['contactTelephone'] : '' ?>" required/></td>
							</tr>	
							<tr>	
								<td><label for="contactFax">Fax</label></td>
								<td><input type="number" min="1000000000" max="9999999999" oninvalid="setCustomValidity('Plz enter valid fax number ')" name="contactFax" id="contactFax" value="<?= isset($this->params['contactFax']) ?  $this->params['contactFax'] : '' ?>"/></td>
							</tr>	
							<tr>	
								<td><label title='Email for Purchase Order' for="contactEmail">E-Mail *</label></td>
								<td><input title='Email for Purchase Order' type="email" name="contactEmail" id="contactEmail" value="<?= isset($this->params['contactEmail']) ?  $this->params['contactEmail'] : '' ?>" required/></td>
							</tr>	
							<tr>	
								<td><label title='10 Digits - (Only if self employed)' for="selfAssesmentTaxNo">Self Assessment Tax No. *</label></td>
								<td><input title='10 Digits - (Only if self employed)' type="number" min="100000000" max="9999999999" oninvalid="setCustomValidity('Plz enter valid tax number ')" name="selfAssesmentTaxNo" id="selfAssesmentTaxNo" value="<?= isset($this->params['selfAssesmentTaxNo']) ?  $this->params['selfAssesmentTaxNo'] : '' ?>" required/> </td>
							</tr>						
							<tr>	
								<td><label title='9 Numeric digits, may be prefixed by GB - Required for any UK company (not self employed)' for="vatNumber">Vat Number *</label></td>
								<td><input title='9 Numeric digits, may be prefixed by GB - Required for any UK company (not self employed)' type="number" min="100000000" max="999999999" oninvalid="setCustomValidity('Plz enter valid vat number ')" name="vatNumber" id="vatNumber" value="<?= isset($this->params['vatNumber']) ?  $this->params['vatNumber'] : '' ?>" required/></td>
							</tr>
						</table>	
					</div>   
				</div> 
		 </div>
		</div>
		
		 <div class="panel panel-info">
			<div class="panel-heading"><h4>Remit Details (if different)</h4></div>
		 
		 <div class="panel-body" id="remit">
		     <div class="row">
		        <div class="col-md-6 pull-left">
					<table>
						<tr>
							<td><label for='sameAsAddress'>Same As Above</label></td>
							<td><input type='checkbox' value='1' id='sameAsAddress' id="sameAsAddress"/></td>
						</tr>
						<tr>
							<td><label for="remitAddress">Remit Address *</label></td>
							<td><input type="text" name="remitAddress" id="remitAddress" value="<?= isset($this->params['remitAddress']) ?  $this->params['remitAddress'] : '' ?>" required/></td>
						</tr>
						<tr>
							<td><label for="remitAddress2">Remit Address 2</label></td>
							<td><input type="text" name="remitAddress2" id="remitAddress2" value="<?= isset($this->params['remitAddress2']) ?  $this->params['remitAddress2'] : '' ?>" /></td>
						</tr>
						<tr>
							<td><label for="remitCity">City *</label></td>
							<td><input type="text" name="remitCity" id="remitCity" value="<?= isset($this->currentForm[6]) ?  $this->currentForm[6] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[6]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="remitCounty">County *</label></td>
							<td><input type="text" name="remitCounty" id="remitCounty" value="<?= isset($this->currentForm[7]) ?  $this->currentForm[7] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[7]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="remitPostcode">Postcode *</label></td>
							<td><input type="number" min="100000" max="999999" oninvalid="setCustomValidity('Plz enter valid  postcode ')" name="remitPostcode" id="remitPostcode" value="<?= isset($this->params['remitPostcode']) ?  $this->params['remitPostcode'] : '' ?>" required/></td>
						</tr>
					</table>	
			   </div>
		        
		        <div class="col-md-6 pull-right">
					<table>
						<tr>
							<td><label class='remitCountry' for="remitCountry">Country *</label></td>
							<td><select class='countryField remitCountry' alt-input ='remitAlt' name="remitCountry" id="remitCountry">
									 
									<?php 
									
									$this->params['remitCountry'] = (isset($this->params['remitCountry'])) ? $this->params['remitCountry'] : 'gb';
									
									foreach($this->countries as $code => $name) {
										
										$selected = (isset($this->params['remitCountry']) && $this->params['remitCountry'] == $code) ? 'selected="selected"' : '';
										
										echo '<option value="'.$code.'" '.$selected.' >'.$name.'</option>';
									  
									} ?>
								
								</select></td>
						</tr>
						<tr>
							<td><label for="remitOtherCountry" class='otherCountryField remitAlt'>Please Specify </label></td>
							<td><input type="text" class='otherCountryField remitAlt' name="remitOtherCountry" id="remitOtherCountry" value="<?= isset($this->currentForm[8]) ?  $this->currentForm[8] : '' ?>" /></td>
							<td>  
								<?php if($this->errorLog[8]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="remitTelephone">Telephone *</label></td>
							<td><input type="number" min="1000000000" max="9999999999" oninvalid="setCustomValidity('Plz enter valid telephone number ')" name="remitTelephone" id="remitTelephone" value="<?= isset($this->params['remitTelephone']) ?  $this->params['remitTelephone'] : '' ?>" required/></td>
						</tr>
						<tr>
							<td><label for="remitFax">Fax</label></td>
							<td><input type="number" min="1000000000" max="9999999999" oninvalid="setCustomValidity('Plz enter valid fax number ')" name="remitFax" id="remitFax" value="<?= isset($this->params['remitFax']) ?  $this->params['remitFax'] : '' ?>" /></td>
						</tr>
						<tr>
							<td><label title='Email for Remittance' for="remitEmail">E-Mail *</label></td>
							<td><input title='Email for Remittance' type="email" name="remitEmail" id="remitEmail" value="<?= isset($this->params['remitEmail']) ?  $this->params['remitEmail'] : '' ?>" required/></td>
						</tr>
					</table>	
				</div>
		    </div>
		 </div>
		</div>
		
		<div class="panel panel-info">
			<div class="panel-heading"><h4>Payment Terms</h4></div>
		 
		 <div class="panel-body" id="paymentTerms">
		    <div class="row">
		        <div class="col-md-6 pull-left">
					<table>
						<tr>
							<td><label for="agreedPaymentTerms">Agreed Payment Terms *</label></td>
							<td><select id="agreedPaymentTerms" name="agreedPaymentTerms">
							
								<?php 
								
								$this->params['agreedPaymentTerms'] = (isset($this->params['agreedPaymentTerms'])) ? $this->params['agreedPaymentTerms'] : 'n060';
								
								foreach($this->paymentTerms as $code => $name) {
									
									$selected = (isset($this->params['agreedPaymentTerms']) && $this->params['agreedPaymentTerms'] == $code) ? 'selected="selected"' : '';
									
									echo '<option value="'.$code.'" '.$selected.' >'.$name.'</option>';
								  
								} ?>

							</select></td>
						</tr>
						<tr>
							<td><label for="incoTerms">INCO Terms *</label></td>
							<td><input type="text" name="incoTerms" value="<?= isset($this->params['incoTerms']) ?  $this->params['incoTerms'] : 'DDP/GB' ?>" /></td>
						</tr>
						<tr>
							<td><label for="currency">Currency *</label></td>
							<td><select name="currency" id="currency" >
							
								<?php 
								
								$this->params['currency'] = (isset($this->params['currency'])) ? $this->params['currency'] : 'gbp';
								
								foreach($this->currencies as $code => $name) {
									
									$selected = (isset($this->params['currency']) && $this->params['currency'] == $code) ? 'selected="selected"' : '';
									
									echo '<option value="'.$code.'" '.$selected.' >'.$name.'</option>';
								  
								} ?>
							
							</select></td>
						</tr>
						<tr>
							<td><label for="currency" class='otherCurrency'>Please Specify *</label></td>
							<td><input type='text' name='otherCurrency' value="<?= isset($this->currentForm[9]) ?  $this->currentForm[9] : '' ?>" class='otherCurrency' id='otherCurrency' /></td>
							<td>  
								<?php if($this->errorLog[9]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
					</table>	
			  </div>
		        
		        <div class="col-md-6 pull-right">
					<table>
						<tr>
							<td><label for="directDebit">Direct Debit</label></td>
							<?php
							//strip off text from code
							$paymentType = (isset($this->params['paymentType']))?$this->params['paymentType']:'';
											
							$checked = ($paymentType == 'u')?'checked':'';
							?>

							<td><input type="checkbox" <?=$checked?> name="directDebit" id="directDebit" value="u" />
						</tr>
						<tr>
							<td><label for="paymentType">Payment Type</label></td>
							<td><input type="text" disabled name="paymentType" id="paymentType" value="bp"/></td>
						</tr>
					</table>	
			   </div>
		    </div>
		 </div>
		 </div>
		 
		 <div class="panel panel-info">
			<div class="panel-heading"><h4>Bank Details</h4></div>
			
		 <div class="panel-body" id="bankDetails">
		    <div class="row">
		    	<p style='margin:0 0 0 15px;font-size:14px'>
		    		<b>Backup documentation from the supplier to support the bank details is mandatory, refer to 'Help' documentation for further details</b>
	    		</p>
		        <div class="col-md-6 pull-left">
					<table>
						<tr>
							<td><label for="bankName">Bank Name *</label></td>
							<td><input type="text" id="bankName" name="bankName" value="<?= isset($this->currentForm[10]) ?  $this->currentForm[10] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[10]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="bankBranch">Bank Branch *</label></td>
							<td><input type="text" id="bankBranch" name="bankBranch" value="<?= isset($this->currentForm[11]) ?  $this->currentForm[11] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[11]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="bankAddress">Bank Address *</label></td>
							<td><input type="text" id="bankAddress" name="bankAddress" value="<?= isset($this->params['bankAddress']) ?  $this->params['bankAddress'] : '' ?>" required/></td>
						</tr>
						<tr>
							<td><label for="bankCity">City *</label></td>
							<td><input type="text" id="bankCity" name="bankCity" value="<?= isset($this->currentForm[12]) ?  $this->currentForm[12] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[12]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="bankPostcode">Postcode *</label></td>
							<td><input type="number" min="100000" max="999999" oninvalid="setCustomValidity('Plz enter valid postcode ')" id="bankPostcode" name="bankPostcode" value="<?= isset($this->params['bankPostcode']) ?  $this->params['bankPostcode'] : '' ?>" required/></td>
						</tr>
					</table>
		        </div>
				
		        <div class="col-md-6 pull-right">
					<table>
						<tr>
							<td><label for="bankCounty">County/Region *</label>
							<td><input type="text" id="bankCounty" name="bankCounty" value="<?= isset($this->currentForm[13]) ?  $this->currentForm[13] : '' ?>" required/></td>
							<td>  
								<?php if($this->errorLog[13]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="bankCountry">Country *</label>
							<td><select name="bankCountry" id="bankCountry" alt-input='bankAlt' class='countryField'>
								
								<?php 
								
								$this->params['bankCountry'] = (isset($this->params['bankCountry'])) ? $this->params['bankCountry'] : 'gb';
								
								foreach($this->countries as $code => $name) {
									
									$selected = (isset($this->params['bankCountry']) && $this->params['bankCountry'] == $code) ? 'selected="selected"' : '';
									
									echo '<option value="'.$code.'" '.$selected.' >'.$name.'</option>';
								  
								} ?>
								
							</select></td>
						</tr>
						<tr>
							<td><label for="bankOtherCountry" class='otherCountryField bankAlt'>Please Specify *</label></td>
							<td><input type="text" class='otherCountryField bankAlt' name="bankOtherCountry" id="bankOtherCountry" value="<?= isset($this->currentForm[14]) ?  $this->currentForm[14] : '' ?>"/></td>
							<td>  
								<?php if($this->errorLog[14]){?>
								<span class="error"><?php echo "numbers are not allowed"?> </span>
<?php }?></td>
						</tr>
						<tr>
							<td><label for="accountNumber">Account Number *</label></td>
							<td><input type="number" min="10000000000" oninvalid="setCustomValidity('Plz enter valid account number ')" id="accountNumber" name="accountNumber" value="<?= isset($this->params['accountNumber']) ?  $this->params['accountNumber'] : '' ?>" required/></td>
						</tr>
						<tr>
							<td><label for="sortCode">Sort/Swift/Routing Code *</label></td>
							<td><input type="number" oninvalid="setCustomValidity('Plz enter valid routing code ')" id="sortCode" name="sortCode" value="<?= isset($this->params['sortCode']) ?  $this->params['sortCode'] : '' ?>" required/> </td>
						</tr>
					</table>	
				</div>
		    </div>
		 </div>
		</div> 
		 
		 <div class="panel panel-info">
			<div class="panel-heading"><h4>Attachment</h4></div>
			
		 <div class="panel-body" id="attachmentSubmit">
		    <div class="row">
		        <div class="col-md-6 pull-left">
		        	<div class="form-group">
						<label for="attachment">Attachment 1 *</label>
						<input type="file" name="attachment" value="<?= isset($this->params['attachment']) ?  $this->params['attachment'] : '' ?>" required/>
					</div>
			   </div>
		        <div class="col-md-6 pull-right">
					<div class="form-group">
						<label for="attachment2">Attachment 2</label>
						<input type="file" name="attachment2" value="<?= isset($this->params['attachment2']) ?  $this->params['attachment2'] : '' ?>" />
					</div>
			  </div>

		    </div>
		 </div>
		</div>
		
		<div class="row col-md-8 col-md-offset-4">
			<button onclick='window.history.back()' class='btn btn-primary btn-lg'>Back</button>
			<input type="reset" class='btn btn-warning btn-lg' value="Clear">
			<button type="submit" class='btn btn-success btn-lg'>Submit</button>
		</div>
	</form>
</div>

<?php echo $this->render('footer.phtml');?>