  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->title ;?></title>
  <?php
		 $this->headScript()->appendFile($this->baseUrl("js/jquery-1.12.4.js"))
							->appendFile($this->baseUrl("js/bootstrap.min.js"))                 
							->appendFile($this->baseUrl("js/myscript.js"));
            echo $this->headScript();
             $this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.min.css"))
			 ->appendStylesheet($this->baseUrl("css/font-awesome.min.css"))
			 ->appendStylesheet($this->baseUrl("css/site.css"));
        echo $this->headLink();
       ?>
  <script src="<?php echo $this->baseUrl ?>/js/jquery-1.12.4.js"></script>
  <script src="<?php echo $this->baseUrl ?>/js/myscript.js"></script>
		 <script src="<?php echo $this->baseUrl ?>/js/jquery-1.12.4.js"></script>
</head>

<body>
<div id="header">
VENDOR REQUEST SYSTEM
</div>