  <nav class="navbar navbar-default">
	<div class=" row col-md-10 col-md-offset-1">
		<ul class="nav navbar-nav navbar-left">
			  <li><a href="<?=$this->baseUrl('/index');?>"><h4>Home</h4></a> </li>
			  <li><a href="<?=$this->baseUrl('/new');?>"><h4>New Request</h4></a></li>
			  <li><a href="<?=$this->baseUrl('/view/template');?>"><h4>Template</h4></a></li>
			  <li><a href="<?=$this->baseUrl('/view/template');?>"><h4>Help</h4></a></li>
			  
		</ul>

		<ul class="nav navbar-nav navbar-right">
			  <li><a><h4 style="color:green;"><span class="glyphicon glyphicon-user"></span> Welcome <?php echo ($this->user); ?></h4></a></li>
			  <li><a href="<?=$this->baseUrl('/authentication/logout');?>"><h4>Logout</h4></a></li>
		</ul>
	</div>
</nav>